version: '3.8'

services:
  web01:
    build:
      context: ../src/web01
      dockerfile: Dockerfile
    container_name: web01
    ports:
      - "4000:80"
    restart: unless-stopped

  web02:
    build:
      context: ../src/web02
      dockerfile: Dockerfile
    container_name: web02
    ports:
      - "4001:80"
    restart: unless-stopped
